### ISSUE TITLE
Curious typesafety loss when returned directly. 

### ISSUE THREAD

**Issue by pnegahdar** [lukemorales/exhaustive#9]
I noticed in the example below, the first function is detected by TypeScript as being type unsafe but the second is not. Any ideas why? 

```typescript
import { exhaustive } from "exhaustive";

export type Copyable =
  | { type: "text"; text: string }
  | { type: "file"; file: File }
  | { type: "url"; url: string; contentType: string };

export type Input = { type: "text"; value: string };

// No Typescript Error
const copyableNotTypeSafe = async (input: Input): Promise<Copyable | null> => {
  return await exhaustive.tag(input, "type", {
    text: async () => {
      return {
        type: "text",
        fieldDNE: "FIELD DOES NOT EXISTS"
      };
    },
    _: async () => null
  });
};

// Typescript correctly detects result is the wrong type 
const copyableTypeSafe = async (input: Input): Promise<Copyable | null> => {
  const result = await exhaustive.tag(input, "type", {
    text: async () => {
      return {
        type: "text",
        fieldDNE: "FIELD DOES NOT EXISTS"
      };
    },
    _: async () => null
  });
  return result;
};
```

Sandbox demo with typescript errors: https://codesandbox.io/s/typescript-playground-export-forked-m27tfl?file=/index.ts

**Comment by lukemorales** [comment]
Thanks for the repro @pnegahdar. I'm not sure why/how Typescript is doing that, but I see what's happening: 

In your first example (when you do `return await exhaustive.tag` or just `return exhaustive.tag`), Typescript is picking the return type from your function `: Promise<Copyable | null>` and adding that value to a union inside the generics in `exhaustive.tag` that would result in the output being `PromiseLike<Copyable | null> | { type: string; fieldDNE: string; }`, hence why it's not failing the type check.

Whereas in your second example, once you store the result of `exhaustive.tag` in a variable, it's already narrowed down to `{ type: string; fieldDNE: string; }`, making it incompatible with the expected return type of your function once you do `return result`.

I'm still trying to figure out a better way to pass a generic to `exhaustive.tag` that would define the expected return type for each property, but in the mean time, you can ensure better type-safety by defining the return type on each property:

```ts
// (input: Input) => Promise<Copyable | null>
const copyableNowTypeSafe = async (input: Input) => {
  return await exhaustive.tag(input, "type", {
    text: async (): Promise<Copyable> => {
      return {
        type: "text",
        fieldDNE: "FIELD DOES NOT EXISTS"
      };
    },
    _: async () => null
  });
};
```

**Comment by pnegahdar** [comment]
Thanks for looking into it @lukemorales. To be honesty I wasn't sure if it was better to report to the typescript folks or this library. I'm still leaning more towards TS as those two should be functionally the same. 

Anyway I did the necessary workarounds. Thanks for this library!

**Comment by lukemorales** [comment]
@pnegahdar I just released https://github.com/lukemorales/exhaustive/releases/tag/v1.1.2 that will improve and fix the example you shared.
